#!/usr/bin/env python3
"""Package configuration for build_database."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
WEBAPP = ROOT / 'MIFPAPP' / 'CORE'
DATABASE_DIR = ROOT / 'MIFPAPP' / 'DATABASE'
DEFAULT_JSONL_DIR = ROOT / 'SCRAPERS' / 'OUTPUTS'
ASSETS_DIR = DATABASE_DIR / 'assets'

# Singleton page canonical URLs
SINGLETON_CANONICAL = {
    'code_of_conduct': ['https://old.mifp.eu/mifp-code-of-conduct'],
    'privacy': ['https://old.mifp.eu/mifp-privacy-policy', 'https://old.mifp.eu/join-us-privacy-policy'],
    'manifesto': ['https://old.mifp.eu/manifesto-of-solidarity'],
}

# Noise lines to filter out
NOISE_LINES = {
    '© 2010-2022 mediterranean institute of fundamental physics',
    '© 2010-2021 mediterranean institute of fundamental physics',
    '© mediterranean institute of fundamental physics',
    'powered by aruba', 'cookie policy', 'i accept', 'accept all cookies',
    'manage cookies', 'cookie settings', 'functional cookies', 'analytical cookies',
    'read more', 'scopri di pi', 'leggi tutto', 'show more',
    'facebook', 'twitter', 'linkedin', 'youtube', 'instagram',
    'share this', 'share on', 'tweet', 'post on', 'email this',
    'print this page', 'back to top', 'back to home',
    'all rights reserved', 'all rights are reserved',
    'this site uses cookies', 'we use cookies',
    'scroll down', 'scroll for more',
    'latest news', 'more news', 'previous', 'next', 'next page', 'prev page',
    'page 1', 'page 2', 'page 3', 'page 4', 'page 5',
    'search...', 'search this site',
    'subscribe', 'subscribe to our newsletter',
    'follow us', 'follow me',
    'send', 'submit', 'cancel', 'close', 'ok', 'okay',
    'home icon', 'menu icon', 'search icon',
    'powered by joomla', 'joomla', 'joomla!',
    'template', 'template by', 'designed by',
    'visitors', 'visits', 'page views', 'hit counter',
    'last updated', 'last modified', 'updated on',
    'popular', 'most read', 'most viewed',
    'related articles', 'related posts',
    'comments', 'leave a comment', 'no comments',
    'category', 'categories', 'tags', 'tagged with',
    'archive', 'archives', 'older posts', 'newer posts',
}

# Country name inference hints
COUNTRY_HINTS = {
    'italy': 'Italy', 'italia': 'Italy', 'rome': 'Italy', 'roma': 'Italy', 'tor vergata': 'Italy',
    'sapienza': 'Italy', 'cnr': 'Italy', 'politecnico': 'Italy', 'milano': 'Italy', 'pisa': 'Italy',
    'naples': 'Italy', 'napoli': 'Italy', 'trento': 'Italy', 'bologna': 'Italy', 'padova': 'Italy',
    'genova': 'Italy', 'salerno': 'Italy', 'aquila': 'Italy', "l'aquila": 'Italy', 'vicenza': 'Italy',
    'perugia': 'Italy', 'palermo': 'Italy', 'catania': 'Italy', 'frascati': 'Italy', 'trieste': 'Italy',
    'lecco': 'Italy', 'ferrara': 'Italy', 'modena': 'Italy', 'parma': 'Italy', 'udine': 'Italy',
    'cagliari': 'Italy', 'bari': 'Italy', 'lecce': 'Italy', 'siena': 'Italy', 'verona': 'Italy',
    'infn': 'Italy', 'ictp': 'Italy',
    'france': 'France', 'paris': 'France', 'cnrs': 'France', 'montpellier': 'France', 'grenoble': 'France',
    'toulouse': 'France', 'lyon': 'France', 'marseille': 'France', 'nantes': 'France', 'strasbourg': 'France',
    'nice': 'France', 'bordeaux': 'France', 'lille': 'France', 'saclay': 'France', 'cachan': 'France',
    'european synchrotron': 'France', 'ill': 'France', 'esrf': 'France',
    'normale supérieure': 'France', 'normale superieure': 'France', 'ecole normale': 'France',
    'paul cezanne': 'France', 'paul cézanne': 'France', 'charles coulomb': 'France',
    'cadi ayyad': 'Morocco', 'monastir': 'Tunisia',
    'cern': 'Switzerland', 'geneve': 'Switzerland', 'switzerland': 'Switzerland', 'swiss': 'Switzerland',
    'zurich': 'Switzerland', 'bern': 'Switzerland', 'basel': 'Switzerland', 'lausanne': 'Switzerland',
    'epfl': 'Switzerland', 'eth': 'Switzerland',
    'germany': 'Germany', 'berlin': 'Germany', 'munich': 'Germany', 'münchen': 'Germany',
    'hamburg': 'Germany', 'stuttgart': 'Germany', 'dortmund': 'Germany', 'bonn': 'Germany', 'cologne': 'Germany',
    'koln': 'Germany', 'frankfurt': 'Germany', 'dresden': 'Germany', 'heidelberg': 'Germany', 'aachen': 'Germany',
    'karlsruhe': 'Germany', 'tubingen': 'Germany', 'tübingen': 'Germany', 'julich': 'Germany', 'freiburg': 'Germany',
    'gottingen': 'Germany', 'göttingen': 'Germany', 'leipzig': 'Germany', 'hannover': 'Germany', 'potsdam': 'Germany',
    'magdeburg': 'Germany', 'braunschweig': 'Germany', 'darmstadt': 'Germany', 'bremen': 'Germany',
    'fraunhofer': 'Germany', 'max planck': 'Germany', 'mpg': 'Germany', 'mpi': 'Germany',
    'unam': 'Mexico', 'mexico': 'Mexico', 'mexico city': 'Mexico', 'cdmx': 'Mexico',
    'uk': 'United Kingdom', 'united kingdom': 'United Kingdom', 'england': 'United Kingdom',
    'london': 'United Kingdom', 'oxford': 'United Kingdom', 'cambridge': 'United Kingdom',
    'manchester': 'United Kingdom', 'edinburgh': 'United Kingdom', 'glasgow': 'United Kingdom',
    'southampton': 'United Kingdom', 'bristol': 'United Kingdom', 'birmingham': 'United Kingdom',
    'nottingham': 'United Kingdom', 'leeds': 'United Kingdom', 'liverpool': 'United Kingdom',
    'sheffield': 'United Kingdom', 'cardiff': 'United Kingdom', 'bath': 'United Kingdom',
    'durham': 'United Kingdom', 'warwick': 'United Kingdom',
    'exeter': 'United Kingdom', 'surrey': 'United Kingdom', 'sussex': 'United Kingdom',
    'kent': 'United Kingdom', 'reading': 'United Kingdom', 'leicester': 'United Kingdom',
    'hull': 'United Kingdom', 'aberdeen': 'United Kingdom', 'dundee': 'United Kingdom',
    'strathclyde': 'United Kingdom', 'heriot-watt': 'United Kingdom', 'queen mary': 'United Kingdom',
    'ucl': 'United Kingdom', 'imperial': 'United Kingdom', 'kings college': 'United Kingdom',
    'king\'s college': 'United Kingdom',
    'usa': 'United States', 'united states': 'United States', 'america': 'United States',
    'new york': 'United States', 'california': 'United States', 'massachusetts': 'United States',
    'harvard': 'United States', 'mit': 'United States', 'stanford': 'United States', 'caltech': 'United States',
    'berkeley': 'United States', 'ucla': 'United States', 'ucsb': 'United States', 'ucsd': 'United States',
    'uc irvine': 'United States', 'uc davis': 'United States', 'cornell': 'United States',
    'princeton': 'United States', 'yale': 'United States', 'columbia': 'United States',
    'chicago': 'United States', 'illinois': 'United States', 'michigan': 'United States',
    'texas': 'United States', 'colorado': 'United States', 'washington': 'United States',
    'boston': 'United States', 'pennsylvania': 'United States', 'penn state': 'United States',
    'ohio': 'United States', 'florida': 'United States', 'arizona': 'United States',
    'georgia tech': 'United States', 'georgia institute': 'United States',
    'purdue': 'United States', 'northwestern': 'United States', 'duke': 'United States',
    'johns hopkins': 'United States', 'carnegie': 'United States', 'nist': 'United States',
    'los alamos': 'United States', 'lanl': 'United States', 'sandia': 'United States',
    'brookhaven': 'United States', 'bnl': 'United States', 'argonne': 'United States',
    'fermilab': 'United States', 'jpl': 'United States', 'nasa': 'United States',
    'russia': 'Russia', 'russian': 'Russia', 'moscow': 'Russia', 'saint-petersburg': 'Russia',
    'st. petersburg': 'Russia', 'st petersburg': 'Russia', 'novosibirsk': 'Russia',
    'ioffe': 'Russia', 'ras': 'Russia', 'siberian': 'Russia', 'kazan': 'Russia',
    'bauman': 'Russia', 'moscow state': 'Russia', 'moscow institute': 'Russia',
    'spain': 'Spain', 'españa': 'Spain', 'espana': 'Spain', 'madrid': 'Spain', 'barcelona': 'Spain',
    'valencia': 'Spain', 'sevilla': 'Spain', 'bilbao': 'Spain', 'granada': 'Spain',
    'zaragoza': 'Spain', 'csic': 'Spain', 'icfo': 'Spain', 'icn2': 'Spain', 'icmab': 'Spain',
    'china': 'China', 'beijing': 'China', 'shanghai': 'China', 'hong kong': 'China',
    'shenzhen': 'China', 'guangzhou': 'China', 'nanjing': 'China', 'chengdu': 'China',
    'wuhan': 'China', 'westlake': 'China', 'fudan': 'China', 'tsinghua': 'China',
    'peking': 'China', 'zhejiang': 'China', 'shanghaitech': 'China',
    'japan': 'Japan', 'tokyo': 'Japan', 'kyoto': 'Japan', 'osaka': 'Japan', 'nagoya': 'Japan',
    'sendai': 'Japan', 'sapporo': 'Japan', 'tsukuba': 'Japan', 'yokohama': 'Japan',
    'kobe': 'Japan', 'hiroshima': 'Japan', 'riken': 'Japan', 'nict': 'Japan',
    'netherlands': 'Netherlands', 'holland': 'Netherlands', 'amsterdam': 'Netherlands',
    'utrecht': 'Netherlands', 'leiden': 'Netherlands', 'delft': 'Netherlands',
    'groningen': 'Netherlands', 'rotterdam': 'Netherlands', 'eindhoven': 'Netherlands',
    'nijmegen': 'Netherlands', 'twente': 'Netherlands', 'wageningen': 'Netherlands',
    'austria': 'Austria', 'vienna': 'Austria', 'wien': 'Austria', 'graz': 'Austria',
    'linz': 'Austria', 'innsbruck': 'Austria', 'salzburg': 'Austria',
    'belgium': 'Belgium', 'brussels': 'Belgium', 'leuven': 'Belgium', 'antwerp': 'Belgium',
    'ghent': 'Belgium', 'gent': 'Belgium', 'liege': 'Belgium', 'liège': 'Belgium',
    'imec': 'Belgium', 'vib': 'Belgium',
    'sweden': 'Sweden', 'stockholm': 'Sweden', 'gothenburg': 'Sweden', 'göteborg': 'Sweden',
    'lund': 'Sweden', 'uppsala': 'Sweden', 'linkoping': 'Sweden', 'linköping': 'Sweden',
    'kth': 'Sweden', 'chalmers': 'Sweden',
    'denmark': 'Denmark', 'copenhagen': 'Denmark', 'københavn': 'Denmark', 'aarhus': 'Denmark',
    'odense': 'Denmark', 'lyngby': 'Denmark', 'dtu': 'Denmark', 'nbi': 'Denmark',
    'norway': 'Norway', 'oslo': 'Norway', 'bergen': 'Norway', 'trondheim': 'Norway',
    'stavanger': 'Norway', 'ntnu': 'Norway',
    'finland': 'Finland', 'helsinki': 'Finland', 'espoo': 'Finland', 'tampere': 'Finland',
    'turku': 'Finland', 'oulu': 'Finland', 'aalto': 'Finland',
    'poland': 'Poland', 'warsaw': 'Poland', 'warszawa': 'Poland', 'krakow': 'Poland', 'kraków': 'Poland',
    'wroclaw': 'Poland', 'wrocław': 'Poland', 'poznan': 'Poland', 'poznań': 'Poland',
    'gdansk': 'Poland', 'gdańsk': 'Poland', 'lodz': 'Poland', 'łódź': 'Poland',
    'portugal': 'Portugal', 'lisbon': 'Portugal', 'lisboa': 'Portugal', 'porto': 'Portugal',
    'coimbra': 'Portugal', 'braga': 'Portugal',
    'greece': 'Greece', 'athens': 'Greece', 'athina': 'Greece', 'thessaloniki': 'Greece',
    'heraklion': 'Greece', 'crete': 'Greece', 'forth': 'Greece',
    'czech': 'Czech Republic', 'czech republic': 'Czech Republic', 'prague': 'Czech Republic',
    'praha': 'Czech Republic', 'brno': 'Czech Republic', 'ostrava': 'Czech Republic',
    'plzen': 'Czech Republic',
    'hungary': 'Hungary', 'budapest': 'Hungary', 'debrecen': 'Hungary', 'szeged': 'Hungary',
    'pecs': 'Hungary', 'pécs': 'Hungary',
    'romania': 'Romania', 'bucharest': 'Romania', 'bucuresti': 'Romania', 'cluj': 'Romania',
    'timisoara': 'Romania', 'timisoara': 'Romania', 'iasi': 'Romania',
    'bulgaria': 'Bulgaria', 'sofia': 'Bulgaria', 'plovdiv': 'Bulgaria', 'varna': 'Bulgaria',
    'croatia': 'Croatia', 'zagreb': 'Croatia', 'split': 'Croatia', 'rijeka': 'Croatia',
    'pula': 'Croatia', 'dubrovnik': 'Croatia', 'jozef stefan': 'Slovenia',
    'slovenia': 'Slovenia', 'ljubljana': 'Slovenia', 'maribor': 'Slovenia',
    'ireland': 'Ireland', 'dublin': 'Ireland', 'cork': 'Ireland', 'galway': 'Ireland',
    'tcd': 'Ireland', 'ucd': 'Ireland', 'tyndall': 'Ireland',
    'turkey': 'Turkey', 'turkiye': 'Turkey', 'istanbul': 'Turkey', 'ankara': 'Turkey',
    'izmir': 'Turkey', 'sabanci': 'Turkey', 'sabancı': 'Turkey', 'koc': 'Turkey', 'koç': 'Turkey',
    'israel': 'Israel', 'tel aviv': 'Israel', 'jerusalem': 'Israel', 'haifa': 'Israel',
    'rehovot': 'Israel', 'weizmann': 'Israel', 'hebrew': 'Israel', 'ben gurion': 'Israel',
    'technion': 'Israel',
    'india': 'India', 'mumbai': 'India', 'bombay': 'India', 'delhi': 'India', 'bangalore': 'India',
    'bengaluru': 'India', 'chennai': 'India', 'madras': 'India', 'hyderabad': 'India',
    'kolkata': 'India', 'calcutta': 'India', 'pune': 'India', 'iit': 'India',
    'taiwan': 'Taiwan', 'taipei': 'Taiwan', 'hsinchu': 'Taiwan', 'tainan': 'Taiwan',
    'ntu': 'Taiwan', 'national tsing hua': 'Taiwan', 'academia sinica': 'Taiwan',
    'korea': 'South Korea', 'south korea': 'South Korea', 'seoul': 'South Korea',
    'daejeon': 'South Korea', 'busan': 'South Korea', 'incheon': 'South Korea',
    'kaist': 'South Korea', 'postech': 'South Korea', 'ibs': 'South Korea',
    'singapore': 'Singapore', 'nus': 'Singapore', 'ntu singapore': 'Singapore',
    'australia': 'Australia', 'sydney': 'Australia', 'melbourne': 'Australia', 'brisbane': 'Australia',
    'perth': 'Australia', 'adelaide': 'Australia', 'canberra': 'Australia', 'anu': 'Australia',
    'brazil': 'Brazil', 'brasil': 'Brazil', 'sao paulo': 'Brazil', 'rio de janeiro': 'Brazil',
    'campinas': 'Brazil', 'unicamp': 'Brazil', 'unesp': 'Brazil',
    'argentina': 'Argentina', 'buenos aires': 'Argentina', 'cordoba': 'Argentina', 'la plata': 'Argentina',
    'cuba': 'Cuba', 'havana': 'Cuba', 'la habana': 'Cuba',
    'slovakia': 'Slovakia', 'bratislava': 'Slovakia',
    'belarus': 'Belarus', 'belarusian': 'Belarus', 'minsk': 'Belarus',
    'ukraine': 'Ukraine', 'kiev': 'Ukraine', 'kyiv': 'Ukraine', 'kharkiv': 'Ukraine', 'lemp': 'Ukraine',
    'armenia': 'Armenia', 'yerevan': 'Armenia',
    'georgia country': 'Georgia', 'tbilisi': 'Georgia',
    'egypt': 'Egypt', 'cairo': 'Egypt', 'giza': 'Egypt',
    'iran': 'Iran', 'tehran': 'Iran', 'sharif': 'Iran', 'isfahan': 'Iran',
    'saudi arabia': 'Saudi Arabia', 'riyadh': 'Saudi Arabia', 'kaust': 'Saudi Arabia',
    'uae': 'United Arab Emirates', 'dubai': 'United Arab Emirates', 'abudhabi': 'United Arab Emirates',
    'serbia': 'Serbia', 'belgrade': 'Serbia', 'beograd': 'Serbia', 'novi sad': 'Serbia',
    'eu': 'European Union', 'europa': 'European Union', 'unione': 'European Union',
    'university': 'University', 'universita': 'University', 'università': 'University', 'universiteit': 'University',
    'université': 'University', 'universitat': 'University', 'universidad': 'University', 'universite': 'University',
    'katholieke': 'University', 'univ': 'University', 'univ.': 'University', 'uni': 'University', 'college': 'College',
    'college': 'College', 'uni': 'University', 'academia': 'Academia', 'academy': 'Academy', 'research': 'Research',
    'institute': 'Institute', 'institut': 'Institute', 'instituto': 'Institute', 'instituci': 'Institute', 'institute': 'Institute',
    'laboratorio': 'Laboratory', 'laboratorio': 'Laboratory', 'lab': 'Laboratory', 'lab.': 'Laboratory',
    'group': 'Group', 'gruppo': 'Group', 'team': 'Team', 'company': 'Company', 'corporation': 'Corporation',
    'inc': 'Incorporated', 'ltd': 'Ltd', 'gmbh': 'GmbH', 'srl': 'srl', 'spa': 'spa', 'llc': 'LLC',
    'association': 'Association', 'association': 'Association', 'associazione': 'Association',
    'foundation': 'Foundation', 'foundation': 'Foundation', 'fondazione': 'Foundation', 'centro': 'Center',
    'centre': 'Center', 'center': 'Center', 'centro': 'Center', 'center': 'Center', 'progetto': 'Project',
    'project': 'Project', 'programma': 'Program', 'program': 'Program', 'workshop': 'Workshop',
    'conference': 'Conference', 'meeting': 'Meeting', 'symposium': 'Symposium', 'school': 'School',
}

# User agent for fetching assets
FETCH_UA = "curl/8.5.0"

# System keywords to filter
SYSTEM_KEYWORDS = {'cookie', 'cookies', 'privacy', 'password', 'login', 'logout', 'accessibility', 'sitemap', 'search', 'terms', 'conditions'}

# Navigation pollution triggers
NAV_TRIGGERS = {'home', 'events', 'news', 'publications', 'members', 'about', 'contacts', 'login', 'register', 'search', 'sitemap', 'privacy', 'cookies', 'sponsors', 'join us', 'become a member', 'code of conduct', 'scientific council'}
